name: Main test pipeline
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
          
      - name: Install Dependencies
        run: npm ci
        
      - name: Setup chrome driver environment
        run: |
         sudo apt-get update # Remove if running outside container
         sudo apt-get clean # Remove if running outside container
         sudo apt-get install -y wget # Remove if running outside container
         sudo wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add - # Remove if running outside container
         sudo echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list # Remove if running outside container
         sudo apt-get -y update # Remove if running outside container
         sudo apt-get install -y google-chrome-stable # If not running in docker then run this line with sudo
         VERSION=`google-chrome --version | egrep -o '[0-9]+.[0-9]+' | head -1` # Get chrome version that we just installed
         npm i webdriver-manager@latest -D # Install webdriver manager locally
         npm i chromedriver --chromedriver_version=$VERSION -D # Install chrome driver to the version that we got from google chrome installation above
        
      - name: Lint
        run: npm run lint

      - name: Test
        run: |
          npm test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
          npm run e2e -- --protractor-config=e2e/protractor-ci.conf.js
